### ISSUE TITLE
Automa: implementare metodi e inner Class che implementano State

### ISSUE THREAD

**Issue by angelitadoria** [AndreaTangucci/Eserc-CRUD1-gruppo3#3]

**Comment by angelitadoria** [comment]
implementato con commit 0a09d055d80647f03dc87e4dc411d0b4ba43c1b1

**Comment by angelitadoria** [comment]
commit parziale b6a22e601c49a1c485cd93a250399cfcb9efb077

**Comment by AndreaTangucci** [comment]
Risolto con commit 98f89122465b03b8421683bcd9d11297de95b39b
